name: Build and Deploy to KurocoFront

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Export static site
        run: npm run generate

      - name: Copy to public
        run: |
          mkdir -p public
          cp -r .output/public/* public/
